Update, Delete, Aggregate
Nelofarzabi/vet-clinic pull request #5
Opened 2023-09-20 06:01 UTC by Nelofarzabi

![268995721-76d67bdb-07a5-451d-9fe8-d4478f33538f](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/149611fb-9021-4c0d-b2ea-446dda6a5336)
![268995751-af90523e-274e-45cd-985e-a222d4399aeb](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/132b6117-90a3-4582-aed4-885644adc292)
![268995826-ce7180e9-6728-40e0-93c1-7d8a55f35dd6](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/313441c8-b445-49db-9437-d2f5497e8e12)
![268995884-1a233af1-9fc9-41e8-8294-18a6d2315344](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/8c5e7446-df97-4dd6-8d79-4b32901c801a)
![268995895-a349d221-47e7-47af-b017-da46118e07c8](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/5b4d80ea-8713-4a74-beaf-6b8833b1ef43)
![268995898-e7f1e1ad-e433-4bad-95b7-20fa71422633](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/17d7406e-0da4-44be-bbca-cee54bc09985)
![268995910-e91e9fe3-d0da-4933-9988-e63bd23100df](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/3fdf6fe7-2b0f-41dd-b030-293d31992e62)
![268995921-020eaa37-42f3-49f7-8ebb-26c8dc5f66a0](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/8c70deee-10a0-4b24-a071-158f57027382)
![268995933-f43b4af8-9ce7-4840-8373-4c8cf25aa744](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/3fa03138-2393-4a74-8865-8cf9478b32e2)
![268995947-1306b5eb-5fe5-486a-94ac-08fb3eb42f3d](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/14aa7495-2c09-4e48-a83b-1e440c1bb422)
![268995976-1779b886-622f-45c0-9a3e-6c30754fdc0b](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/e9b5d6ac-20df-4a58-92d2-de3018b85436)
![268995987-81053e7f-cbac-431e-bd16-fc0c5fb7a3a1](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/d1ca1925-7e4d-48fd-bda7-e167435d3ce1)
![268995993-9a7120b7-dc7c-427d-bf56-d9f9b9c04d4b](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/7a41f7c4-64df-4ef5-a249-b3af2ccbb51b)
![268996008-40ca0534-8658-445e-bddb-f98c7ed8ac37](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/07c2738a-e8ed-49c4-bcc1-e6bc3997cb6a)
![268996018-9b8fdbb4-5aef-4577-9d67-45cf676a9476](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/2a39fec4-b975-4b3a-ad4c-246041110b86)
![268996028-201b0741-8484-4c66-b2ae-c43c3dca85d2](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/6a7180ad-9b66-4fae-8f3d-01652932789a)
![268996041-5b6fc76f-49bb-4716-b74e-98179560fe9b](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/4beb00df-c892-4d91-81ec-66b79df7ccea)
![268996050-488b657f-e184-493d-8693-a5da3f547cdb](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/357ce8d0-6c4e-4277-a16d-3ad51f448cb3)
![268996061-c22b50c7-3464-4699-a491-4c822a348d22](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/02c53688-f212-4296-b3a0-3028b7dd47aa)
![268996068-6fa44090-6748-4726-9144-1d9739de1300](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/ba527adc-f21c-471a-97ef-3b75983f7cb7)
![268996074-1ccbf144-bd45-42b1-b12b-9050e74a890a](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/175f2846-75ce-4c8d-8ad7-03cc6a5ac295)
![268996074-1ccbf144-bd45-42b1-b12b-9050e74a890a](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/bd5e546c-6ebc-4eb9-a1e6-3a52253ed81f)
![268996078-8be3be66-a359-47d6-957c-bb416e0ce1c8](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/80b2e386-63fb-45f4-a07e-8aeb7dbfe078)
![268996082-0f3cd997-e0a0-4cea-b5b2-a2e03fda1d88](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/8a58c3da-4b31-4b55-9e55-c1528d69bc11)
![268996089-b65b5752-27b8-451e-979a-48940bba8982](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/804b1dcb-f14e-46dd-9fb7-cb973410e02a)
![268996098-3a6e565c-c1bb-4de9-8bd1-20d9e2f2b35f](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/f4c2f5a0-b5bd-4bb4-adac-3e4219fccf43)
![268996108-ff777808-c724-44ea-b1ea-bb31d8b058e6](https://github.com/Nelofarzabi/vet-clinic/assets/83637292/22011ac0-10d4-4edd-8ce7-3866dde12852)

In this PR, the folowing were affected;

- Added a column species of type string to your animals table. Modify your schema.sql file.
- Inserted new sets of data
- Created TRANSACTIONS to update and delete from table
- Wrote queries for aggregate functions

2023-09-20 07:51 UTC, topeogunleye requested changes
Hi @Nelofarzabi, 

Good job so far!,
Hey there! I've just gone through your SQL project, and I'm really impressed by what I see. You've nailed several key elements of database management, and it's clear that you have a solid understanding of SQL syntax and functionality. 🤩🚀

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
### Outstanding Work on the SQL Project! 🌟👏

#### Phenomenal Highlights:

1. **File Organization**: You have meticulously followed the project guidelines by organizing your SQL code into separate files for schema, data, and queries. This shows not just your technical skills, but also your ability to read and adhere to specifications. 📝✅
  
2. **Schema Design**: Your ALTER TABLE command to add a new species column with VARCHAR(255) is spot-on. You've demonstrated great understanding of how to modify database schemas. 🛠️💪

3. **Data Insertions**: The way you populated the `animals` table is flawless. Your INSERT INTO statements are well-formed, and the sample data you used is not only appropriate but also quite imaginative! This will help with data testing later on. 🐾🎉
  
4. **Attention to Detail**: Your usage of different data types, such as strings for names and booleans for the `neutered` field, show a deep understanding of how data should be structured. This is foundational for database integrity and query performance. 👀🌟

5. **Data Diversity**: I love how you varied the data for escape attempts, neutered status, and weights. This attention to detail makes your sample database rich for querying and shows that you're thinking like a real-world developer. 🌍👨‍💻

6. **Great Commenting**: Although SQL commands are relatively straightforward, the neatness of your code makes it even easier to understand. And when code is easy to understand, it's easier to maintain. 📚🔍

Your work here is an exemplary demonstration of how to properly manage databases, from modifying schema to data insertion. I am thrilled by your submission and can't wait to see what you come up with next! 🌠🔥

Keep up the amazing work!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 07:51 UTC, topeogunleye commented on queries.sql
> +WHERE name LIKE '%mon';
Hello! 👋. You've done a good job in utilizing SQL transactions, but there's a small gap to fully meet the project requirements. 📝

#### Highlights:
- You've correctly initiated a transaction using `BEGIN`.
- Your `UPDATE` query for setting the `species` column to 'unspecified' is spot on! 👏

#### Areas for Improvement:
- According to the project requirements, you are explicitly asked to include steps to verify that the change was made and then rolled back. Your code lacks the `SELECT` queries that confirm these steps.

Here's how you could improve it:

```sql
BEGIN; -- start transaction

UPDATE animals
SET species = 'unspecified'; -- make change

SELECT species from animals; -- 👈 Add this line to verify that change was made

ROLLBACK; -- roll back the change

SELECT species from animals; -- 👈 Add this line to verify that change was undone
```

Please include these additional `SELECT` queries to fully meet the project requirements. Looking forward to your next commit! 🚀

Best,
Temitope

2023-09-20 07:51 UTC, topeogunleye commented on queries.sql
Hello! 👋 Thank you for submitting your code for review. You've done a good job in utilizing SQL transactions, but there's a small gap to fully meet the project requirements. 📝

#### Highlights:
- You've correctly initiated a transaction using `BEGIN`.
- Your `UPDATE` query for setting the `species` column to 'unspecified' is spot on! 👏

#### Areas for Improvement:
- According to the project requirements, you are explicitly asked to include steps to verify that the change was made and then rolled back. Your code lacks the `SELECT` queries that confirm these steps.

Here's how you could improve it:

```sql
BEGIN; -- start transaction

UPDATE animals
SET species = 'unspecified'; -- make change

SELECT species from animals; -- 👈 Add this line to verify that change was made

ROLLBACK; -- roll back the change

SELECT species from animals; -- 👈 Add this line to verify that change was undone
```

Please include these additional `SELECT` queries to fully meet the project requirements. Looking forward to your next commit! 🚀

Best,
Temitope

2023-09-20 07:51 UTC, topeogunleye commented on queries.sql
> +ROLLBACK;
Hello! . You're on the right track with using transactions and the `DELETE` statement. However, there are some minor adjustments needed to fully meet the project requirements. 🛠️

#### Highlights:
- You've initiated a transaction correctly with `BEGIN;`. 🎉
- Your `DELETE FROM animals;` query is spot on for removing all records from the `animals` table. 👍
- Good use of `ROLLBACK;` to undo the deletion operation. 👏

#### Areas for Improvement:
- Verification Missing: The project requirements specify that you should include `SELECT COUNT(*) FROM ANIMALS;` queries before and after the `ROLLBACK;` to verify that records are actually deleted and then restored. These lines are missing in your code.

Here's how you could complete the requirements:

```sql
BEGIN; -- start transaction

DELETE FROM animals; -- Delete all records

SELECT COUNT(*) FROM animals; -- 👈 Add this line to verify that records were deleted

ROLLBACK; -- Roll back the transaction

SELECT COUNT(*) FROM animals; -- 👈 Add this line to verify that records were restored
```

Please make these adjustments and re-submit your code. Looking forward to your next commit! 🚀

Best,
Temitope

2023-09-20 07:51 UTC, topeogunleye commented on queries.sql
> +GROUP BY neutered;
Hello! 👋. You've got some interesting calculations in there, and it's clear you have a good grasp of using `AVG()` and `GROUP BY`. However, your current code does not meet the specific project requirements. 🛠️

#### Highlights:
- Good use of the `AVG()` function to calculate average values. 🌟
- Your `GROUP BY` and `WHERE` clauses are well-structured. 👍

#### Areas for Improvement:
1. **Wrong Criteria**: The project asks for the average number of escape attempts **per animal type** for animals born between 1990 and 2000. You've calculated it based on whether the animals are neutered or not, which is not what was required.

Here's how your code can meet the requirements:

```sql
SELECT species, AVG(escape_attempts) AS AVG_OF_ESCAPE
FROM animals
WHERE date_of_birth BETWEEN '1990-01-01' AND '2000-12-31'
GROUP BY species;
```

Please update your query to align with the project requirements and resubmit your code. Can't wait to see your updated work! 🚀

Best,
Temitope

2023-09-22 02:59 UTC, roshan-bajgain approved these changes
Hi @Nelofarzabi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- Good job on making changes ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 03:00 UTC, merged